In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
import return_clean_text as ct

In [3]:
data=pd.read_csv('./Train/Train.csv').values                        #loading training data
x_test=pd.read_csv('./Test/Test.csv').values[:,0].tolist()   #loading test data and values[:,0] is flatting 2d list into 1d as our cleaning function will not work

In [49]:
x_train=data[:,0].tolist()
y_train=data[:,1]

In [5]:
print(x_train[0])
print(y_train[0])

mature intelligent and highly charged melodrama unbelivebly filmed in China in 1948. wei wei's stunning performance as the catylast in a love triangle is simply stunning if you have the oppurunity to see this magnificent film take it
pos


In [6]:
x_clean = [ct.getCleanReview(i) for i in x_train]        #List Comprehension
xt_clean = [ct.getCleanReview(i) for i in x_test]

# 2.Vectorization

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
cv = CountVectorizer()

x_vec = cv.fit_transform(x_clean).toarray()
print(x_vec)
print(x_vec.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(40000, 65742)


In [9]:
## Vectorization on the test set
xt_vec = cv.transform(xt_clean).toarray()
print(xt_vec)
cv.get_feature_names()
print(xt_vec.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(10000, 65742)


# 3. Multinomial Naive Bayes

In [56]:
from sklearn.naive_bayes import MultinomialNB,BernoulliNB, GaussianNB

In [57]:
mnb = MultinomialNB()
print(mnb)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)


In [52]:
y_train=np.where(y_train=='pos',int(1),y_train)

In [53]:
y_train=np.where(y_train=='neg',int(0),y_train)

In [54]:
y_clean=[]
for i in y_train:
    y_clean.append(i)

In [59]:
# Training 
mnb.fit(x_vec,y_clean)

MemoryError: 