In [1]:
import numpy as np
import gensim
from gensim.models import word2vec
from gensim.models import KeyedVectors
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
from gensim.test.utils import datapath, get_tmpfile
from gensim.scripts.glove2word2vec import glove2word2vec

In [13]:

glove_file=datapath('G:\coding blocks\machine learning\wordembedding word2vec odd one out challenge\glove.6B.50d.txt')
tmp_file = get_tmpfile("G:\coding blocks\machine learning\wordembedding word2vec odd one out challenge\word2vec.txt")
_ = glove2word2vec(glove_file,tmp_file)
model=KeyedVectors.load_word2vec_format(tmp_file)


In [14]:
model.vocab

{'the': <gensim.models.keyedvectors.Vocab at 0x206d1977b48>,
 ',': <gensim.models.keyedvectors.Vocab at 0x206cc724c08>,
 '.': <gensim.models.keyedvectors.Vocab at 0x206d1977c08>,
 'of': <gensim.models.keyedvectors.Vocab at 0x206cc7249c8>,
 'to': <gensim.models.keyedvectors.Vocab at 0x206d1977d88>,
 'and': <gensim.models.keyedvectors.Vocab at 0x206cc724e88>,
 'in': <gensim.models.keyedvectors.Vocab at 0x206d1977208>,
 'a': <gensim.models.keyedvectors.Vocab at 0x206cc724988>,
 '"': <gensim.models.keyedvectors.Vocab at 0x206d1977308>,
 "'s": <gensim.models.keyedvectors.Vocab at 0x206cc724d08>,
 'for': <gensim.models.keyedvectors.Vocab at 0x206d1977408>,
 '-': <gensim.models.keyedvectors.Vocab at 0x206cc724ac8>,
 'that': <gensim.models.keyedvectors.Vocab at 0x206d1977508>,
 'on': <gensim.models.keyedvectors.Vocab at 0x206cc724a48>,
 'is': <gensim.models.keyedvectors.Vocab at 0x206d1977708>,
 'was': <gensim.models.keyedvectors.Vocab at 0x206cc724908>,
 'said': <gensim.models.keyedvectors.Vo

In [15]:
len(model.vocab)

400000

### we can use this method also to load the file

In [10]:
"""
def readFile(file):
    with open(file,'r',encoding='utf-8') as f:
        embedding_d={}
        for line in f:
            values = line.split()
            word = values[0]
            vector = np.array(values[1:],'float32')
            embedding_d[word]=vector
            
    return embedding_d
"""

In [12]:
"""
model = readFile("glove.6B.50d.txt")
model['the']
"""

array([ 4.1800e-01,  2.4968e-01, -4.1242e-01,  1.2170e-01,  3.4527e-01,
       -4.4457e-02, -4.9688e-01, -1.7862e-01, -6.6023e-04, -6.5660e-01,
        2.7843e-01, -1.4767e-01, -5.5677e-01,  1.4658e-01, -9.5095e-03,
        1.1658e-02,  1.0204e-01, -1.2792e-01, -8.4430e-01, -1.2181e-01,
       -1.6801e-02, -3.3279e-01, -1.5520e-01, -2.3131e-01, -1.9181e-01,
       -1.8823e+00, -7.6746e-01,  9.9051e-02, -4.2125e-01, -1.9526e-01,
        4.0071e+00, -1.8594e-01, -5.2287e-01, -3.1681e-01,  5.9213e-04,
        7.4449e-03,  1.7778e-01, -1.5897e-01,  1.2041e-02, -5.4223e-02,
       -2.9871e-01, -1.5749e-01, -3.4758e-01, -4.5637e-02, -4.4251e-01,
        1.8785e-01,  2.7849e-03, -1.8411e-01, -1.1514e-01, -7.8581e-01],
      dtype=float32)

In [16]:
a= model['india']

In [17]:
input_1 = ["elephant","lion","tiger","goat","snake"]

In [18]:
type([a])

list

In [19]:
len([a])

1

In [20]:
a=a.reshape((1,-1))

In [21]:
a.shape

(1, 50)

# we can also find cosine without [a] by reshaping a by(1,50) as list do the same thing

In [22]:
cosine_similarity(a,a)

array([[1.]], dtype=float32)

In [23]:
### after placing .lower() we are not editing word we will return exact word recieved like we will return India with i capital if it is given in india

In [24]:
def odd_one_out(words,word_dict):
    
    all_word_vectors=[word_dict[w.lower()] for w in words]
    avg_vector = np.mean(all_word_vectors,axis=0)
    
    #print(avg_vector.shape)
    
    odd_one_out=None
    min_sim=100.0 # very high value
    
    for w in words:
        sim=cosine_similarity([word_dict[w.lower()]],[avg_vector])
        if sim<min_sim:
            min_sim = sim
            odd_one_out = w
        #print("similarity btw %s and avg vector is %.2f"%(w,sim))
        
    return odd_one_out

In [26]:
odd=odd_one_out(input_1,model)
print(odd)

tiger


In [28]:
input_2=['sofa','door','Cabinet','bed']
odd=odd_one_out(input_2,model)
print(odd)

Cabinet


In [29]:
import pandas as pd

In [30]:
df=pd.read_csv("Test/Test.csv")

In [31]:
df.shape

(20, 5)

In [32]:
df.head(7)

Word1      Word2    Word3      Word4     Word5
0  elephant       lion    tiger       goat     snake
1       man  policeman  fireman    teacher   postman
2     plane       bird   rocket    balloon       cat
3     onion     celery  lettuce  pineapple    potato
4     India   football   hockey    cricket  swimming
5       who        why     what      where        is
6        on         in     over      their       was

In [33]:
model['india']

array([-0.20356 , -0.8707  , -0.19172 ,  0.73862 ,  0.18494 ,  0.14926 ,
        0.48079 , -0.21633 ,  0.72753 , -0.36912 ,  0.13397 , -0.1143  ,
       -0.18075 , -0.64683 , -0.18484 ,  0.83575 ,  0.48179 ,  0.76026 ,
       -0.50381 ,  0.80743 ,  1.2195  ,  0.3459  ,  0.22185 ,  0.31335 ,
        1.2066  , -1.8441  ,  0.14064 , -0.99715 , -1.1402  ,  0.32342 ,
        3.2128  ,  0.42708 ,  0.19504 ,  0.80113 ,  0.38555 , -0.12568 ,
       -0.26533 ,  0.055264, -1.1557  ,  0.16836 , -0.82228 ,  0.20394 ,
        0.089235, -0.60125 , -0.032878,  1.3735  , -0.51661 ,  0.29611 ,
        0.23951 , -1.3801  ], dtype=float32)

In [34]:
a="India"
a.lower()

'india'

In [35]:
print(a)

India


In [36]:
df=df.values

In [37]:
a=[w for w in df[0]]

In [38]:
a

['elephant', 'lion', 'tiger', 'goat', 'snake']

In [39]:
y_pred=[]
for i in range(df.shape[0]):
    words=df[i].tolist()
    y= odd_one_out(words,model)
    y_pred.append(y)

In [40]:
y_pred

['tiger',
 'postman',
 'bird',
 'pineapple',
 'India',
 'who',
 'was',
 'Australia',
 'Money',
 'dance',
 'ship',
 'England',
 'Pool',
 'Egypt',
 'jackal',
 'veil',
 'Universe',
 'Stab',
 'Club',
 'Sun']

In [41]:
y_predict=pd.DataFrame(data=y_pred,columns=['OddOne'])

In [42]:
y_predict.to_csv("odd_one_out_prediction.csv",index=False)